Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -65,24 +65,36 @@ jobs:
         run: |
 
          set +e  # Allow script to continue even if an error occurs
+         EXIT_CODE=0  # Initialize variable to track failures
          
           for i in {100..104}; do
             DB_NAME="tenant$i"
             echo "Running Liquibase for $DB_NAME..."
             
             /opt/liquibase/liquibase --searchPath=/opt --defaults-file=/opt/liquibase/liquibase.properties  --url="jdbc:mariadb://13.212.238.210:3306/$DB_NAME"  update --changelog-file=liquibase/changelog.xml --log-level=debug
-            echo "LIQUIBASE_EXIT_CODE=$?" >> $GITHUB_ENV  # Save exit code to GitHub Actions env variable
+           
+             CODE=$?  # Capture exit code for this iteration
+            if [ $CODE -ne 0 ]; then
+                EXIT_CODE=$CODE  # Store failure code
+            fi
+          done
             
+            echo "LIQUIBASE_EXIT_CODE=$EXIT_CODE" >> $GITHUB_ENV  # Save exit code globally
             set -e  # Enable failing for later steps
           
-          done
 
 
       - name: Run Liquibase Rollback if Update Fails
         if: env.LIQUIBASE_EXIT_CODE != '0'  # Run only if Liquibase failed
         run: |
           echo "⚠️ Update failed! Rolling back changes..."
-          /opt/liquibase/liquibase --searchPath=/opt --defaults-file=/opt/liquibase/liquibase.properties rollback --tag  before_update --changelog-file=liquibase/changelog.xml --log-level=debug   
+           for i in {100..104}; do
+            DB_NAME="tenant$i"
+            echo "Rolling back $DB_NAME..."
+            
+          /opt/liquibase/liquibase --searchPath=/opt --defaults-file=/opt/liquibase/liquibase.properties --url="jdbc:mariadb://13.212.238.210:3306/$DB_NAME" rollback --tag before_update --changelog-file=liquibase/changelog.xml --log-level=debug   
+         
+          done
           echo "✅ Rollback completed!"
             
 
