Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -64,11 +64,16 @@ jobs:
         id: liquibase_update
         run: |
 
+         set +e  # Allow script to continue even if an error occurs
+         
           for i in {100..104}; do
             DB_NAME="tenant$i"
             echo "Running Liquibase for $DB_NAME..."
-  
+            
             /opt/liquibase/liquibase --searchPath=/opt --defaults-file=/opt/liquibase/liquibase.properties  --url="jdbc:mariadb://13.212.238.210:3306/$DB_NAME"  update --changelog-file=liquibase/changelog.xml --log-level=debug
+            echo "LIQUIBASE_EXIT_CODE=$?" >> $GITHUB_ENV  # Save exit code to GitHub Actions env variable
+            
+            set -e  # Enable failing for later steps
           
           done
 
