Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -63,6 +63,62 @@ jobs:
           echo "✅ All backups created successfully!"
 
 
+      - name: Tag Database Before Update
+        run: |
+          TIMESTAMP=$(date +%Y%m%d_%H%M%S)  # Generate unique timestamp
+          for i in {100..104}; do
+            DB_NAME="tenant$i"
+            TAG_NAME="before_update_${TIMESTAMP}"
+            echo "Tagging database: $DB_NAME with tag $TAG_NAME"
+
+           /opt/liquibase/liquibase --searchPath=/opt --defaults-file=/opt/liquibase/liquibase.properties \
+           --url="jdbc:mariadb://13.212.238.210:3306/$DB_NAME" tag "$TAG_NAME"
+      
+          echo "TAG_NAME_$DB_NAME=$TAG_NAME" >> $GITHUB_ENV  # Store tag name per DB  
+          done
+
+
+
+        
+      - name: Run Liquibase Update for All Tenants
+        id: liquibase_update
+        run: |
+
+         set +e  # Allow script to continue even if an error occurs
+         EXIT_CODE=0  # Initialize variable to track failures
+         
+          for i in {100..104}; do
+            DB_NAME="tenant$i"
+            echo "Running Liquibase for $DB_NAME..."
+            
+            /opt/liquibase/liquibase --searchPath=/opt --defaults-file=/opt/liquibase/liquibase.properties  --url="jdbc:mariadb://13.212.238.210:3306/$DB_NAME"  update --changelog-file=liquibase/changelog.xml --log-level=debug
+           
+             CODE=$?  # Capture exit code for this iteration
+            if [ $CODE -ne 0 ]; then
+                EXIT_CODE=$CODE  # Store failure code
+            fi
+          done
+            
+            echo "LIQUIBASE_EXIT_CODE=$EXIT_CODE" >> $GITHUB_ENV  # Save exit code globally
+            set -e  # Enable failing for later steps
+          
+
+
+      - name: Run Liquibase Rollback if Update Fails
+        if: env.LIQUIBASE_EXIT_CODE != '0'  # Run only if Liquibase failed
+        run: |
+          echo "⚠️ Update failed! Rolling back changes..."
+          for i in {100..104}; do
+          DB_NAME="tenant$i"
+          TAG_NAME=$(printenv TAG_NAME_$DB_NAME)  # Retrieve tag name per DB
+
+          echo "Rolling back $DB_NAME to tag $TAG_NAME..."
+          /opt/liquibase/liquibase --searchPath=/opt --defaults-file=/opt/liquibase/liquibase.properties \
+          --url="jdbc:mariadb://13.212.238.210:3306/$DB_NAME" rollback --tag "$TAG_NAME" --changelog-file=liquibase/changelog.xml --log-level=debug   
+          done
+          echo "✅ Rollback completed!"    
+
+
 
     
       - name: Print Success Message
